export const INSURANCE_FIELDS = [
    {
        key: 'insurance_company',
        label: 'Insurance Company',
        type: 'creatable-select',
        required: true,
        section: 'General Information',
        placeholder: 'Select insurance company',
        optionsKey: 'insuranceCompanies',
        createUrl: '/insurance-companies',
    },
    { key: 'insured_name', label: 'Insured Name', type: 'text', required: true, section: 'General Information', placeholder: 'Full name of the insured' },
    {
        key: 'policy_type',
        label: 'Policy Type',
        type: 'creatable-select',
        required: true,
        section: 'General Information',
        placeholder: 'Select policy type',
        optionsKey: 'policyTypes',
        createUrl: '/policy-types',
    },
    { key: 'contact_person', label: 'Contact Person', type: 'text', required: true, section: 'General Information', placeholder: 'Who to reach out to' },
    { key: 'contact_method', label: 'Contact Method', type: 'select', required: true, section: 'General Information' },
    { key: 'contact_value', label: 'Contact Name', type: 'text', required: true, section: 'General Information', placeholder: 'Phone number, email, or username' },
    { key: 'policy_no', label: 'Policy Number', type: 'text', required: true, section: 'General Information', placeholder: 'e.g. POL-2026-0001' },

    { key: 'sum_insured', label: 'Sum Insured', type: 'number', required: true, section: 'Financial Details', placeholder: '0.00' },
    { key: 'premium', label: 'Premium', type: 'number', required: true, section: 'Financial Details', placeholder: '0.00' },
    { key: 'revised_sum_insured', label: 'Revised Sum Insured', type: 'number', required: true, section: 'Financial Details', placeholder: '0.00' },
    { key: 'revised_premium', label: 'Revised Premium', type: 'number', required: true, section: 'Financial Details', placeholder: '0.00' },
    { key: 'revised_premium_rate', label: 'Revised Premium Rate', type: 'number', required: true, section: 'Financial Details', placeholder: '0.000', step: '0.001' },
    { key: 'net_premium', label: 'Net Premium', type: 'number', required: true, section: 'Financial Details', placeholder: '0.00' },

    { key: 'expiry_date', label: 'Expiry Date', type: 'date', required: true, section: 'Dates & Status' },
    { key: 'confirmed_date', label: 'Confirmed Date', type: 'date', required: false, section: 'Dates & Status' },
    { key: 'status', label: 'Status', type: 'select', required: true, section: 'Dates & Status', hideOnCreate: true },
    { key: 'payment_status', label: 'Payment Status', type: 'select', required: true, section: 'Dates & Status', hideOnCreate: true },
    { key: 'payment_date', label: 'Payment Date', type: 'date', required: false, section: 'Dates & Status' },
    { key: 'policy_received_date', label: 'Policy Received Date', type: 'date', required: false, section: 'Dates & Status' },

    { key: 'remarks', label: 'Remarks', type: 'textarea', required: false, section: 'Notes', placeholder: 'Any additional notes (optional)' },
];
