export const INSURANCE_FIELDS = [
    { key: 'insurance_company', label: 'Insurance Company', type: 'text', required: true },
    { key: 'policy_no', label: 'Policy No.', type: 'text', required: true },
    { key: 'contact_method', label: 'Contact Method', type: 'select', required: true },
    { key: 'contact_value', label: 'Contact Value', type: 'text', required: true },
    { key: 'contact_person', label: 'Contact Person', type: 'text', required: true },
    { key: 'insured_name', label: 'Insured Name', type: 'text', required: true },
    { key: 'expiry_date', label: 'Expiry Date', type: 'date', required: true },
    { key: 'policy_type', label: 'Policy Type', type: 'text', required: true },
    { key: 'sum_insured', label: 'Sum Insured', type: 'number', required: true },
    { key: 'premium', label: 'Premium', type: 'number', required: true },
    { key: 'revised_sum_insured', label: 'Revised Sum Insured', type: 'number', required: false },
    { key: 'revised_premium', label: 'Revised Premium', type: 'number', required: false },
    { key: 'revised_premium_rate', label: 'Revised Premium Rate', type: 'number', required: false },
    { key: 'confirmed_date', label: 'Confirmed Date', type: 'date', required: false },
    { key: 'status', label: 'Status', type: 'text', required: false },
    { key: 'request_policy_date', label: 'Request Policy Date', type: 'date', required: false },
    { key: 'policy_received_date', label: 'Policy Received Date', type: 'date', required: false },
    { key: 'remarks', label: 'Remarks', type: 'textarea', required: false },
];
